remote_theme: just-the-docs/just-the-docs
title: SkyCat Documentation
description: Documentation for the SkyCat radio control library
aux_links:
  "SkyCat on GitHub": "https://github.com/yourusername/skycat"
